### ISSUE TITLE
Sending for a second time via principal id sometimes fails

### ISSUE THREAD

**Issue by kanej** [Psychedelic/plug-controller#22]
If you send via principal id twice in a short enough period, the second send fails showing an error screen. No ICP is sent, nor does it appear in the activity list.

A retry succeeds.

## Steps to recreate

* run through the send process, sending to a principal id - complete the process
* immediately rerun through the send process, once again sending to a principal id
* the send errors:
![image](https://user-images.githubusercontent.com/24030/125104407-437f3c80-e0d5-11eb-80c7-9583cadcae2c.png)

**Comment by rocky-fleek** [comment]
Fixed by #21
